# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: seckill-redis
  labels:
    app: seckill
spec:
  ports:
    - port: 3306
  selector:
    app: seckill
    tier: redis
  clusterIP: None
---
#  Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seckill-redis
  labels:
    app: seckill
spec:
  selector:
    matchLabels:
      app: seckill
      tier: redis
  template:
    metadata:
      labels:
        app: seckill
        tier: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /var/lib/redis
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
