# Seckill Service
apiVersion: v1
kind: Service
metadata:
  name: seckill
  labels:
    app: seckill
spec:
  ports:
    - port: 3000
  selector:
    app: seckill
  type: NodePort
---
# Seckill Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seckill
  labels:
    app: seckill
spec:
  selector:
    matchLabels:
      app: seckill
  strategy:             # 策略，默认 RollingUpdate，表示更新 Pod 的时候会以滚动更新的方式逐个更新 Pod
    type: Recreate      # Recreate 表示重建，更新 Pod 的时候会把所有正在运行的 Pod 杀掉，然后重建新的 Pod
  template:
    metadata:
      labels:
        app: seckill
    spec:
      containers:
      - image: ./source-code
        name: seckill
        env:                                    # 应用程序需要的相关配置
        - name: SECKILL_DB_HOST                 # SECKILL_DB_HOST 对应的值从 MySQL 的 Service 获取
          value: seckill-mysql
        - name: SECKILL_DB_PASSWORD             # 数据库密码和 MySQL 获取的方式一样
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3000
          name: seckill