# Seckill Service
apiVersion: v1
kind: Service
metadata:
  name: seckill
  labels:
    app: seckill
spec:
  ports:
    - port: 3000
      targetPort: 80
  selector:
    app: seckill
  type: NodePort
---
# Seckill Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seckill
  labels:
    app: seckill
spec:
  selector:
    matchLabels:
      app: seckill
  strategy:             # 策略，默认 RollingUpdate，表示更新 Pod 的时候会以滚动更新的方式逐个更新 Pod
    type: Recreate      # Recreate 表示重建，更新 Pod 的时候会把所有正在运行的 Pod 杀掉，然后重建新的 Pod
  replicas: 1
  template:
    metadata:
      labels:
        app: seckill
    spec:
      containers:
      - image: usoftglobal/seckill:1.0.0
        name: seckill
        ports:
        - containerPort: 3000
          name: seckill