version: '3'
services:

  ### Mysql container #########################################

  mysql:
      image: mysql:5.7
      ports:
        - "3307:3306"
      volumes:
        - ./mysql_data/:/var/lib/mysql:rw
      restart: always
      privileged: true
      environment:
        MYSQL_ROOT_PASSWORD: root

  ### Redis container #########################################

  redis:
      image: redis:latest
      ports:
        - "6399:6379"
      restart: always
      privileged: true
